name: Debug with tmate

on: [ workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup upterm session
      uses: owenthereal/action-upterm@v1
      with:
        limit-access-to-actor: true  # 限制为仅触发者可通过其 GitHub SSH 密钥连接
